#!/bin/sh

: <<'COMMENT' nestest.log format example 
C000  4C F5 C5  JMP $C5F5                       A:00 X:00 Y:00 P:24 SP:FD CYC:  0
C5F5  A2 00     LDX #$00                        A:00 X:00 Y:00 P:24 SP:FD CYC:  9
C5F7  86 00     STX $00 = 00                    A:00 X:00 Y:00 P:26 SP:FD CYC: 15
C5F9  86 10     STX $10 = 00                    A:00 X:00 Y:00 P:26 SP:FD CYC: 24
C5FB  86 11     STX $11 = 00                    A:00 X:00 Y:00 P:26 SP:FD CYC: 33
C5FD  20 2D C7  JSR $C72D                       A:00 X:00 Y:00 P:26 SP:FD CYC: 42
C72D  EA        NOP                             A:00 X:00 Y:00 P:26 SP:FB CYC: 60
C72E  38        SEC                             A:00 X:00 Y:00 P:26 SP:FB CYC: 66
C72F  B0 04     BCS $C735                       A:00 X:00 Y:00 P:27 SP:FB CYC: 72
C735  EA        NOP                             A:00 X:00 Y:00 P:27 SP:FB CYC: 81
COMMENT

parseline()
{
	PC=0x$1 ; shift

	BYTES=()
	while [ ${#1} -eq 2 ]
	do
		BYTES+=(0x$1) ; shift
	done

	while [[ $1 != A:* ]]
	do 
		shift
	done

	A=0x${1#*:} ; shift
	X=0x${1#*:} ; shift
	Y=0x${1#*:} ; shift
	P=0x${1#*:} ; shift
	SP=0x${1#*:} ; shift

	if [ $1 = CYC: ]
	then
		CYC=$2
	else 
		CYC=${1#*:}
	fi

	IFS=, 
	printf "\tCpuSnapshot{ $PC, { ${BYTES[*]} }, $A, $X, $Y, $P, $SP, $CYC },\n"
	IFS=' '
}

echo '
/*
	This file was autogenerated by "logparse.sh".
	Do not modify it.
*/

#include "../src/cpu.h"

const CpuSnapshot NestestLog[] = {
'

while read -r line
do
	parseline $line
done

echo '
	CpuSnapshot{}
};
'
